# Generated by Django 4.2.30 on 2026-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('bajarilgan', 'Bajarilgan')], default='yangi', max_length=50)),
            ],
        ),
    ]
